language: node_js
node_js:
- '9'
env:
  matrix:
    secure: CTziiKsHYCjdRYftawXT7oBMFm3nOQNRc+ZFv0rUxTaGkw9ImwuxBv6yqMGh6YfykIe94aFNwV+oN8vbuG9NZ56xotAW7mt4r/eCQRnutm54IoJV4SoCdBlgRFPk26nRafnogmDq/pH7lzLI7csDvup0ABF3R6Ysji19vR4LnNIotahdOtyt5jHBnn60XxibluCy6q03Xg2bw1UNjGFN0PVrw5wpPnpB3WugEkyd4Nos5US7q80KC3ltThw1c9TYDz38rryghMnm0lPe1/ruxCMzHx9KLwZl/D3Bikxf2YLaifwphf5NIkAQiAUpaYcMamBZsABxtzE45+TBhSc4sKGJL+ZuFwXAp/gbBbxgtY+9BKHnV78v1+bcAY4Geb8kKAsUgN7Q3Tqk0mjy+L4pML2BXyD5v7x8ev9MRfKbamx1GRX+XvP1pDVLFCHsT4cnPoUoE4SjXma9s6ry0cvN2crkVfRk1KQJhbpYphmQHVfY49nNN77es0Uo+T51w5zHfvzjWwx12C1rauX5s2tdmm3mkSUNgSMsu4egE7LoGARZYqlxRlpmjzvwhDo2jKhMPnOE9lbmH9v6s3BeizMSHbtKDRgpaH1G4dqwC/rL+vIf5ED/Sfm3KEdAVadk0U8E4a3L5jqTYbSLYT1wvYCZmvvt47OKQY9ubuFkhLRht9M=
    secure: MP84r8nsLXPBijsGNglKWZEOvTjVcDJwcsm708S3kw0HxtbYHPfDVxAFV9iCSff9mCCNeUP/uTCw4e0MxzqtoLirj+qzWI8EDqLDxB/YsAdANm5Puq+7QYWvgK6HwYmq8guMfeZuT8DTlzSRPjDMIlUHJsv7rGatoD4BCEYUOs20mDoEkujjWeYoMAF6w/TIm/HukAFO71E2uIGysE77b9/1QbbYLtEF8f94k5mJliWS1sLQ1dGGHrw+mKVdJqB5oueDhJatF/29eEGLxiBOJACn291Xl1Vyfqj+le+7XX4qwvCRAVUySrkLFbVbf1B+lQHCaI4LFrqWsIGrjxk8bT7NRJQSCxi4tqRu96gn8nGFgetMkeryJrtB7G1/AYjBpvjq1VGAhbWWAWZB4fqdsvOPWDD2jBhLCRMWHSZ6cFERddfZScsenu4ksGnBZZ7Gd8zo/86HRakeHVJxwvprei3MW4P9xfR64+CoWAphhDPZivj/N7MBq8HmAva2cZHBajVR7DE+GenmyzcTFWpAwNO3WAcUJL3kGFW1eI4fUY2HPa0kDITdbJ1ryHDn//nTPbDwzWmK5xY71P1zP8kaBJawJ54bYdw/YCd/WNq9pNoknQ6WJu4RUdHBNroVOINZslIWWNWK93M9FVchNerNXaOytYHBD8bVfEhtVnlSzPU=
matrix:
  include:
  - os: linux
    services:
    - docker
    before_install:
    - docker pull debian:latest
    install:
    - docker build --build-arg MAGICLEAP_ARG="$MAGICLEAP" -t niltree .
    - docker run niltree cat niltree-linux-bin.tar.gz >niltree-linux-bin.tar.gz
    - docker run niltree cat niltree-linux-full.tar.gz >niltree-linux-full.tar.gz
    - docker run niltree cat niltree-linux.tar.gz >niltree-linux.tar.gz
  - os: osx
    osx_image: xcode9.2
    before_install:
    - brew install glfw glew
    install:
    - rm -Rf dump
    - npm install -g appdmg
    - curl "https://nodejs.org/dist/v10.3.0/node-v10.3.0-darwin-x64.tar.gz" >node.tar.gz
    - tar -zxf node.tar.gz
    - rm node.tar.gz
    - mv node-v10.3.0-darwin-x64 node
    - export PATH="$(pwd)/node/bin:$PATH"
    - unset NVM_NODEJS_ORG_MIRROR
    - "./node/bin/npm install"
    - install_name_tool -change '@rpath/OpenVR.framework/Versions/A/OpenVR' '@loader_path/../../node_modules/native-openvr-deps/bin/osx64/OpenVR.framework/Versions/A/OpenVR'
      build/Release/exokit.node
    - mkdir -p /tmp/Niltree.app/Contents/MacOS
    - cp -R * /tmp/Niltree.app/Contents/MacOS
    - cp Info.plist /tmp/Niltree.app/Contents
    - tar -czf niltree-macos-full.tar.gz --exclude=".*" --exclude="*.tar.gz" *
    - rm -R node
    - tar -czf niltree-macos.tar.gz --exclude=".*" --exclude="*.tar.gz" *
    - ./niltree-codesign-macos.sh
