version: 0.0.{build}

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "9"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

after_test:
  - ps: |
      wget "https://nodejs.org/dist/v10.3.0/node-v10.3.0-win-x64.zip" -OutFile node.zip
      7z x node.zip
      rm node.zip
      mv node-v10.3.0-win-x64 node
      $env:Path = "$pwd\node;$env:Path";
      .\node\npm install
      rm -R -fo node/node_modules
      set version "$env:APPVEYOR_REPO_TAG_NAME"
      if ([string]::IsNullOrEmpty("$version")) { set version "$env:APPVEYOR_REPO_COMMIT".Substring(0, 8) }
      mkdir dist
      .\buildtools\iscc "$pwd\niltree.iss" "/dMyAppVersion=$version" /odist /qp
      mv dist\*.exe niltree-win-x64.exe
      rm -R -fo dist
      & "C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe" sign /f .\codesign-windows.pfx /t http://timestamp.comodoca.com/authenticode /p "$env:PFX_KEY" niltree-win-x64.exe
      7z a niltree-windows-full.zip * -xr'!.git' -xr'!buildtools' -xr'!niltree-win-x64.exe'
      rm -r -fo node
      7z a niltree-windows.zip * -xr'!.git' -xr'!buildtools' -xr'!niltree-win-x64.exe' -xr'!niltree-windows-full.zip'

artifacts:
  - path: "niltree-windows.zip"
    name: niltree-windows
  - path: "niltree-windows-full.zip"
    name: niltree-windows-full
  - path: "niltree-win-x64.exe"
    name: niltree-windows-installer

deploy:
  - provider: GitHub
    description: 'Niltree git'
    auth_token:
      secure: JzzhsoEKVJ6oKuS/3Uwa+odltY7CFRU/V5BaO62rG6BwfSeCydMDX5o/gJScQGkN
    artifact: "niltree-windows.zip"
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'Niltree git'
    auth_token:
      secure: JzzhsoEKVJ6oKuS/3Uwa+odltY7CFRU/V5BaO62rG6BwfSeCydMDX5o/gJScQGkN
    artifact: "niltree-windows-full.zip"
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'Niltree installer'
    auth_token:
      secure: JzzhsoEKVJ6oKuS/3Uwa+odltY7CFRU/V5BaO62rG6BwfSeCydMDX5o/gJScQGkN
    artifact: "niltree-win-x64.exe"
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

# Don't actually build.
build: off
